context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Guitar FX (Arena 2000)"
            node.latency      = "10/1000"
            capture.props = {
                node.name       = "guitar_fx.capture"
                target.object   = "alsa_input.usb-Donner_Arena_2000_Audio-00.analog-stereo"
                audio.channels  = 2
                audio.position  = [ FL FR ]
                node.passive    = true
                stream.dont-remix = true
            }
            playback.props = {
                node.name       = "guitar_fx.playback"
                media.class     = "Stream/Output/Audio"
                target.object   = "alsa_output.pci-0000_03_00.1.hdmi-stereo"
                audio.channels  = 2
                audio.position  = [ FL FR ]
            }
        }
    }
]
